#  create-package.yml
#  Created: 2024/09/15 - 08:10
#  Altered: qui 19 fev 2026 21:40:30 -04
#  Updated: dom 01 mar 2026 03:46:54 -04
#
#  Copyright (c) 2024-2026, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
name: VoidBR Build Package

#concurrency:
#  group: build-iso-${{ github.workflow }}
#  cancel-in-progress: false

# Gatilhos para o workflow
on:
  #  push:
  #    branches: ["main"]
  pull_request:
  workflow_dispatch: # Permite a execução manual do workflow
    inputs:
      tmate: # Input para habilitar o modo de depuração
        type: boolean
        description: "With TMATE"
        required: false
        default: false
      packager:
        type: string
        description: "Empacotador"
        required: true
        default: "Vilmar Catafesta <vcatafesta@gmail.com>"
      repository:
        type: string
        description: "Repositorio para construir"
        required: true
        default: "voidlinuxbr/repo"
  repository_dispatch: # Permite a execução através de eventos de webhook
    types:
      - webhook
      - "**"

  #  schedule:  # Executa automaticamente toda sexta-feira às 05:00
  #    - cron: '0 5 * * 5'

env:
  GITHUB_TOKEN: "${{ secrets.ORGANIZATION_TOKEN }}"
  TM_VOIDBR_DEV_1: "${{ secrets.VOIDBR_PACKAGES_TOKEN_BOT }}"
  TM_VOIDBR_DEV_2: "${{ secrets.CHAT_ID }}"
  TM_VOIDBR_DEV_3: "${{ secrets.MESSAGE_THREAD_ID_PACKAGE }}"
  TM_VOIDBR_BR_1: "${{ secrets.VOIDBR_BR_PACKAGES_TOKEN_BOT}}"
  TM_VOIDBR_BR_2: "${{ secrets.VOIDBR_BR_PACKAGES_CHAT_ID}}"
  TM_VOIDBR_BR_3: "${{ secrets.VOIDBR_BR_PACKAGES_MESSAGE_THREAD_ID}}"
  SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
  SERVER_HOST: "${{ secrets.SERVER_HOST }}"
  SERVER_USER: "${{ secrets.SERVER_USER }}"
  SERVER_PORT: "${{ secrets.SERVER_PORT }}"
  PKGMAKE_PRIVATE_KEY: "${{ secrets.PKGMAKE_PRIVATE_KEY }}"
  PKGMAKE_PACKAGER: "${{ github.event.client_payload.packager || inputs.packager || 'Vilmar Catafesta <vvcatafesta@gmail.com>' }}"
  DEBUG: "${{ github.event.client_payload.tmate || inputs.tmate || false }}"
  REPOSITORY: "${{ github.event.client_payload.repository || inputs.repository }}"
  ISO_DISTRONAME: "voidbr"
  STARTED_BY_USER: "${{ github.actor }}"
  TRIGGERED_BY_USER: "${{ github.triggering_actor }}"
  TARGET_REPOSITORY: "${{github.event_name == 'workflow_dispatch' && inputs.repository || github.event.client_payload.repository}}"
  FULL_PACKAGE_NAME: ''
  #LANG: pt_BR.UTF-8
  #LC_ALL: pt_BR.UTF-8

jobs:
  #debug:
  #  runs-on: self-hosted
  #  steps:
  #  - name: Dump do evento
  #    run: echo '${{ toJson(github.event) }}'

  setup:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    outputs:
      time: ${{ steps.time.outputs.time }} # Saída do job
      REPOSITORY_NAME: ${{ steps.get-repo-name.outputs.repo_name }}
      RELEASE_TAG: ${{ steps.set_vars.outputs.RELEASE_TAG }}
    steps:
      - name: Set VARS manually
        id: set_vars
        shell: bash
        run: |
          # Set release tag manually
          RELEASE_TAG="${release_tag:-$(date '+%Y%m%d-%H%M')}"
          echo "RELEASE_TAG=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          echo "RELEASE_TAG=$RELEASE_TAG" >> "$GITHUB_ENV"
          echo "KERNEL_VERSION=6.12.74_1" >> "$GITHUB_OUTPUT"
          echo "KERNEL_VERSION=6.12.74_1" >> "$GITHUB_ENV"
          echo "ISO_BASENAME=voidbr-live-$iso_edition-x86_64-$KERNEL_VERSION_$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          echo "ISO_BASENAME=voidbr-live-$iso_edition-x86_64-$KERNEL_VERSION_$RELEASE_TAG" >> "$GITHUB_ENV"

      - name: Set up volume directory in HOST
        shell: bash
        run: |
          #Set up volume directory in HOST
          sudo mkdir -p /voidrepo/mnt/lfs
          sudo mkdir -p /voidrepo/void-mirror/extra

  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    env:
      #DEBUG: false
      TERM: xterm
    # 2. Subir container VoidLinux e instalar tmate
    container:
      image: vcatafesta/voidlinux-docker:1.5 #seg 16 fev 2026 23:52:08 -04
      options: -v ${{ github.workspace }}:/workspace --privileged
      volumes:
        - /voidrepo/mnt/lfs:/mnt/lfs
        - /voidrepo/void-mirror/extra:/voidrepo/void-mirror/extra
    steps:
      - name: Obter a hora atual
        id: time
        shell: bash
        run: |
          #Obter a hora atual
          #echo "::set-output name=time::$(date +'%Y.%m.%d-%H%M')"
          echo "time=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Capturar hora de início do workflow
        id: start-time
        shell: bash
        run: |
          START_TIME=$(date +"%Y-%m-%d %H:%M:%S")  # Hora completa
          START_TIMESTAMP=$(date +%s)  # Timestamp em segundos
          echo "Início do Workflow: $START_TIME"
          echo "START_TIME=$START_TIME"             >> $GITHUB_ENV
          echo "START_TIMESTAMP=$START_TIMESTAMP"   >> $GITHUB_ENV
          echo "START_TIME='$START_TIME'"           >> shared_file.txt
          echo "START_TIMESTAMP='$START_TIMESTAMP'" >> shared_file.txt

      - name: Create Global Helpers Script - Definir a função send_telegram_message no script temporário
        shell: bash
        run: |
          #Definir a função send_telegram_message no script temporário
          sudo rm -rf /tmp/send_telegram_message.sh  # Remove se for diretório
          cat << 'EOF' > /tmp/send_telegram_message.sh
          export TERM=${TERM:-xterm}
          export TERM=${TERM:-xterm-256color}

          #Definindo variáveis de cores
          export reset="\033[0m"
          export rst="\033[0m"
          export green="\033[01;32m"
          export red="\033[01;31m"
          export blue="\033[01;34m"
          export cyan="\033[01;36m"
          export pink="\033[01;35m"
          export yellow="\033[01;33m"
          alias ls='ls -lha --color=auto'
          alias dir='ls -lha --color=auto'

          die() {
            local msg="$1"
            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
            echo -e "BP=>${cyan}error: ${red}${msg}${reset}"
            exit  1
          }
          export -f die

          msg() {
            local msg="$1"
            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
            echo -e "BIV=>${cyan}running: ${yellow}${msg}${reset}"
          }

          msg_tab() {
            local msg="$1"
            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
            echo -e "BIV=>${cyan}info   : ${yellow}${msg}${reset}"
          }

          msg_raw() {
            local msg="$1"
            # Remove tags HTML, se existirem
            #msg="$(sed 's/<[^>]*>//g' <<< "$msg")"

            # Verifica se existe ':' na mensagem
            if [[ "$msg" == *:* ]]; then
              # Divide a string antes e depois do primeiro ':'
              local before_colon="${msg%%:*}:"
              local after_colon="${msg#*: }"
              # Aplica as cores
              msg="${cyan}${before_colon} ${yellow}${after_colon}${reset}"
            else
              # Se não houver ':', aplica apenas a cor padrão
              msg="${cyan}${msg}${reset}"
            fi
            echo -e "$msg"
          }
          export -f msg_raw

          msg_ok() {
            local msg="$1"
            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
            echo -e "BP=>${cyan}feito  : ${green}${msg}${reset}"
          }
          export -f msg_ok

          msg_run() {
            local msg="$*"
            echo -e "BP=>${cyan}running: ${yellow}${msg}${reset}"

            # Executa o comando e captura o código de saída
            if ! eval "$msg"; then
              echo -e "BP=>${red}Erro ao executar: ${yellow}${msg}${reset}" >&2
              return 1
            fi
            return 0
          }
          export -f msg_run

          msg_info() {
            local msg="$1"
            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
            echo -e "BIV=>${yellow}info   : ${cyan}${msg}${reset}"
          }

          msg_warning() {
            local msg="$1"
            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
            echo -e "BIV=>${red}warning: ${orange}${msg}${reset}"
          }

          replicate() {
            local char=${1:-'#'}
            local nsize=${2:-$(tput cols)}
            local line
            printf -v line "%*s" "$nsize" && echo -e "${blue}${line// /$char}${reset}"
          }
          export -f replicate

          function send_telegram_msg() {
            local message="$1"
            local parse_mode="$2"

            # Define parse_mode como "MarkdownV2" se não for especificado
            [[ -z $parse_mode ]] && parse_mode="HTML"

            link_action="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
            MESSAGE="🔗 ${link_action}"
            MESSAGE="${{ github.workflow }} - $message
            <a href=\"${link_action}\">▶ Job #${GITHUB_RUN_NUMBER}</a>
            <pre>
            Triggered     : ${STARTED_BY_USER}
            Inicio        : $START_TIME
            Distroname    : $ISO_DISTRONAME
            Release       : $FULL_PACKAGE_NAME
            Tmate         : $DEBUG
            Package Name  : $TARGET_REPOSITORY
            </pre>"

            # Remove as tags HTML e exibe o resultado no terminal
            echo -e "${green}$(sed 's/<[^>]*>//g' <<< "$MESSAGE")${reset}"
            # Envia a mensagem original com HTML para o Telegram
            curl -s -X POST "https://api.telegram.org/bot${TM_VOIDBR_DEV_1}/sendMessage" \
              -d chat_id="${TM_VOIDBR_DEV_2}" \
              -d message_thread_id="${TM_VOIDBR_DEV_3}" \
              -d text="${MESSAGE}" \
              -d parse_mode="HTML" || true

            curl -s -X POST "https://api.telegram.org/bot${TM_VOIDBR_BR_1}/sendMessage" \
              -d chat_id="${TM_VOIDBR_BR_2}" \
              -d message_thread_id="${TM_VOIDBR_BR_3}" \
              -d text="${MESSAGE}" \
              -d parse_mode="HTML" || true

          }
          export -f send_telegram_msg

          function send_telegram_message() {
            local message="$1"
            local parse_mode="$2"

            # Define parse_mode como "MarkdownV2" se não for especificado
            [[ -z $parse_mode ]] && parse_mode="HTML"

            link_action=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
            MESSAGE="🚀 <b>${{ github.workflow }}</b>
            <pre>
            Job         : #${GITHUB_RUN_NUMBER}
            Workflow    : ${{ github.workflow }}
            Triggered   : ${STARTED_BY_USER}
            Inicio      : $START_TIME
            Distroname  : $ISO_DISTRONAME
            Edition     : $iso_edition
            Kernel      : $KERNEL_VERSION
            Release     : $RELEASE_TAG
            Tmate       : $DEBUG
            ISO Name    : $ISO_BASENAME
            </pre>
            <b>Link:</b> <a href='${link_action}'>Visualizar no GitHub</a>"

            MESSAGE="${{ github.workflow }} - $message
            <b>Job           :</b> <a href='${link_action}'>#${GITHUB_RUN_NUMBER}</a>
            <b>Workflow file :</b> <a href='${wf_url}'>${wf_file}</a>
            <b>Triggered     :</b> <code>${STARTED_BY_USER}/${TRIGGERED_BY_USER}</code>
            <b>Start         :</b> <code>${START_TIME}</code>
            <b>End           :</b> <code>${END_TIME}</code>
            <b>Duration      :</b> <code>${hours}h ${minutes}m ${seconds}s</code>
            <b>Distroname    :</b> <code>${ISO_DISTRONAME}</code>
            <b>Iso Profile   :</b> <code>${iso_profile}</code>
            <b>Edition       :</b> <code>${iso_edition}</code>
            <b>Build dir     :</b> <code>${PROFILE_PATH}</code>
            <b>Release       :</b> <code>${RELEASE_TAG}</code>
            <b>Kernel        :</b> <code>${KERNEL_VERSION}</code>
            <b>Tmate         :</b> <code>${DEBUG}</code>
            <b>Tam ISO       :</b> <code>${iso_size}</code>
            <b>Download      :</b> <a href='${DOWNLOAD_URL_ISO}'>${ISO_BASE_NAME}.iso</a> <code>(${iso_size})</code>
            <b>Download      :</b> <a href='${DOWNLOAD_URL_ISO}'>${ISO_BASE_NAME}.iso.md5</a> <code>(${iso_size})</code>
            <b>Download      :</b> <a href='${DOWNLOAD_URL_ZIP}'>${ISO_BASE_NAME}.zip</a> <code>(${iso_size})</code>
            <b>Download      :</b> <a href='${DOWNLOAD_URL_GZ}'>${ISO_BASE_NAME}.tar.gz</a> <code>(${iso_size})</code>"

            # Envia a mensagem original com HTML para o Telegram
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN_BOT}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d message_thread_id="${TELEGRAM_MESSAGE_THREAD_ID}" \
              -d text="${MESSAGE}" \
              -d parse_mode="HTML"
          }
          export -f send_telegram_message
          EOF
          chmod +x /tmp/send_telegram_message.sh

      - name: Enviar notificação inicial para o Telegram
        shell: bash
        run: |
          source /tmp/send_telegram_message.sh
          replicate
          msg "- name: Enviar notificação inicial para o Telegram"

          msg_tab "ISO_BRANCH='$iso_branch'"
          msg_tab "ISO_BRANCH='$iso_branch'"
          echo "ISO_BRANCH='$iso_branch'" >> GITHUB_ENV
          echo "ISO_BRANCH='$iso_branch'" >> shared_file.txt

          MESSAGE="🚀 <b>[step 1/3] - Iniciando construcao do pacote $TARGET_REPOSITORY</b>"
          send_telegram_msg "$MESSAGE"
          replicate

      - name: update
        run: |
          xbps-install -Syu xbps
          xbps-install --update --yes voidbr-pkgmake void-utils tmate openssh git glibc-locales shfmt
          vinstall -Scc

      - name: Configurar locale
        shell: bash
        run: |
          source /tmp/send_telegram_message.sh
          echo "pt_BR.UTF-8 UTF-8" > /etc/default/libc-locales
          xbps-reconfigure -f glibc-locales || true
          export LANG=pt_BR.UTF-8
          export LANGUAGE=pt_BR.UTF-8
          cp -Rpa /root/. $HOME/. || true

      # 3. Iniciar sessão tmate imediatamente dentro do container
      - name: Setup TMATE Session in CONTAINER
        uses: mxschmitt/action-tmate@v3
        if: ${{ env.DEBUG == 'true' }}
        with:
          install-dependencies: false
          detached: true

      - name: Checkout do repositório atual
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create private.pem
        shell: bash
        run: |
          rm -rf /root/.ssh || true
          mkdir -p /root/.ssh || true

          {
            echo "Host repo"
            echo "  HostName $SERVER_HOST"
            echo "  Port $SERVER_PORT"
            echo "  User $SERVER_USER"
            echo "  IdentityFile ~/.ssh/id_rsa"
            echo "  IdentitiesOnly yes"
          }  > /root/.ssh/config

          echo "$PKGMAKE_PRIVATE_KEY" > /root/.ssh/private.pem
          echo "$PKGMAKE_PRIVATE_KEY" > /root/.ssh/privkey.pem
          printf '%s\n' "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
          chmod 700 /root/.ssh || true
          chmod 600 /root/.ssh/private.pem || true
          chmod 600 /root/.ssh/privkey.pem || true
          chmod 600 /root/.ssh/id_rsa || true
          ssh-keygen -y -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pub || true
          rm /root/.ssh/known_hosts || true
          ssh-keyscan -p "$SERVER_PORT" repo.chililinux.com >> /root/.ssh/known_hosts
          ssh-keyscan -p "$SERVER_PORT" 147.93.38.151 >> /root/.ssh/known_hosts
          ssh-keyscan -p "$TS_VOIDREPO_PORT" "$TS_VOIDREPO_HOST" >> /root/.ssh/known_hosts 2>/dev/null || true
          chmod 600 /root/.ssh/known_hosts || true

      - name: Create .chili-make-repo.conf
        shell: bash
        run: |
          {
            echo "[void]"
            echo "GPGKEY=A0D5A8312A83940ED8B04B0F4BAC871802E960F1"
            echo "SECRETKEY=lg63771588@"
            echo "local_PATH=/voidrepo/void-mirror/extra"
            echo "remote_HOST=repo.chililinux.com"
            echo "remote_USER=$SERVER_USER"
            echo "remote_PATH=/home/$SERVER_USER/domains/chililinux.com/public_html/void/current"
            echo "remote_PORT=$SERVER_PORT"
            echo "PACKAGER='Vilmar Catafesta <gmail.com>'"
            echo "prefix_DB=void"
          } > /root/.chili-make-repo.conf

      - name: Checkout do pacote recebido
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPOSITORY }}
          token: ${{ secrets.ORGANIZATION_TOKEN }}
          fetch-depth: 1
          path: pkgmake

      - name: Build pkg ${{ env.TARGET_REPOSITORY }}
        shell: bash
        run: |
          source /tmp/send_telegram_message.sh
          cd pkgmake/pkgfile
          export LANG=pt_BR.UTF-8
          export LANGUAGE=pt_BR.UTF-8
          pkgver=$(date +%Y%m%d)
          pkgrel=$(date +%H%M)
          export pkgver pkgrel
          if pkgmake -s \
            --packager "$PKGMAKE_PACKAGER" \
            --pkgdest /voidrepo/void-mirror/extra
            source PKGFILE
            PKG_EXT='xbps'
            FETCH_RE='-[^-]+[0-9]+[^.]*.xbps$'
            #FULL_PACKAGE_NAME=$(find /voidrepo/void-mirror/extra -type f -iname "${pkgname}*.$PKG_EXT" \
            #| sort -Vr \
            #| awk -F "$FETCH_RE" '!seen[$1]++')
            FULL_PACKAGE_NAME=$(ls -t /voidrepo/void-mirror/extra/${pkgname}*.xbps | head -n1)
            echo "FULL_PACKAGE_NAME=$FULL_PACKAGE_NAME" >> "$GITHUB_ENV"
          then
            MESSAGE="✅ <b>[step 2/3] - Pacote construido</b>"
          else
            MESSAGE="❌ <b>[step 2/3] - Falha ao construir pacote</b>"
          fi
          send_telegram_msg "$MESSAGE"

      - name: Sincronizar pacote com repositorio remoto
        if: ${{ success() }}
        shell: bash
        run: |
          source /tmp/send_telegram_message.sh
          pkgmake --pkgdest /voidrepo/void-mirror/extra \
                  --reindex-all
          chili-make-repo -A void

      - name: Notificar sucesso
        if: ${{ success() }}
        shell: bash
        run: |
          source /tmp/send_telegram_message.sh
          MESSAGE="✅ <b>[step 3/3] - Build finalizado com sucesso!</b>"
          send_telegram_msg "$MESSAGE"

      - name: Notificar erro
        if: ${{ failure() }}
        shell: bash
        run: |
          source /tmp/send_telegram_message.sh
          MESSAGE="❌ <b>[step 3/3] - Falha no build. Verifique os logs.</b>"
          send_telegram_msg "$MESSAGE"
